library(data.table)

columns_selected <- c("IN_AGUA_POTAVEL", "IN_AGUA_REDE_PUBLICA", "IN_AGUA_POCO_ARTESIANO", "IN_AGUA_CACIMBA", "IN_AGUA_FONTE_RIO", "IN_AGUA_INEXISTENTE", "IN_ESGOTO_REDE_PUBLICA", "IN_ESGOTO_FOSSA_SEPTICA", "IN_ESGOTO_FOSSA_COMUM", "IN_ESGOTO_FOSSA", "IN_ESGOTO_INEXISTENTE", "IN_LIXO_SERVICO_COLETA", "IN_LIXO_QUEIMA", "IN_LIXO_ENTERRA", "IN_LIXO_DESTINO_FINAL_PUBLICO", "IN_LIXO_DESCARTA_OUTRA_AREA", "IN_AREA_VERDE", "IN_BANHEIRO", "IN_BANHEIRO_FUNCIONARIOS", "IN_EQUIP_TV", "QT_EQUIP_TV", "IN_EQUIP_LOUSA_DIGITAL", "QT_EQUIP_LOUSA_DIGITAL", "IN_EQUIP_MULTIMIDIA", "QT_EQUIP_MULTIMIDIA", "IN_DESKTOP_ALUNO", "QT_DESKTOP_ALUNO", "IN_COMP_PORTATIL_ALUNO", "QT_COMP_PORTATIL_ALUNO", "IN_TABLET_ALUNO", "QT_TABLET_ALUNO", "IN_INTERNET", "IN_INTERNET_ALUNOS", "IN_INTERNET_ADMINISTRATIVO", "IN_INTERNET_APRENDIZAGEM", "IN_INTERNET_COMUNIDADE", "IN_ACESSO_INTERNET_COMPUTADOR", "IN_ACES_INTERNET_DISP_PESSOAIS", "TP_REDE_LOCAL", "IN_BANDA_LARGA")

escolas <- fread("dados/microdados_educacao_basica_2020/DADOS/escolas.CSV",
                 select = columns_selected)

write.csv(escolas, "escolas_elida.csv")
