library(rpivotTable)
library(dplyr)
library(readr)
library(readxl)
library(data.table)

getwd()

setwd("~/Downloads/prestacao_de_contas_eleitorais_orgaos_partidarios_2018_17-9-2018")


prest_AC <- fread(file = "despesas_contratadas_orgaos_partidarios_2018_AC.csv")
prest_AL <- fread(file = "despesas_contratadas_orgaos_partidarios_2018_AL.csv")
prest_AM <- fread(file = "despesas_contratadas_orgaos_partidarios_2018_AM.csv")
prest_AP <- fread(file = "despesas_contratadas_orgaos_partidarios_2018_AP.csv")
prest_BA <- fread(file = "despesas_contratadas_orgaos_partidarios_2018_BA.csv")
prest_BR <- fread(file = "despesas_contratadas_orgaos_partidarios_2018_BR.csv")
prest_CE <- fread(file = "despesas_contratadas_orgaos_partidarios_2018_CE.csv")
prest_DF <- fread(file = "despesas_contratadas_orgaos_partidarios_2018_DF.csv")
prest_ES <- fread(file = "despesas_contratadas_orgaos_partidarios_2018_ES.csv")
prest_GO <- fread(file = "despesas_contratadas_orgaos_partidarios_2018_GO.csv")
prest_MA <- fread(file = "despesas_contratadas_orgaos_partidarios_2018_MA.csv")
prest_MG <- fread(file = "despesas_contratadas_orgaos_partidarios_2018_MG.csv")
prest_MS <- fread(file = "despesas_contratadas_orgaos_partidarios_2018_MS.csv")
prest_MT <- fread(file = "despesas_contratadas_orgaos_partidarios_2018_MT.csv")
prest_PA <- fread(file = "despesas_contratadas_orgaos_partidarios_2018_PA.csv")
prest_PB <- fread(file = "despesas_contratadas_orgaos_partidarios_2018_PB.csv")
prest_PE <- fread(file = "despesas_contratadas_orgaos_partidarios_2018_PE.csv")
prest_PI <- fread(file = "despesas_contratadas_orgaos_partidarios_2018_PI.csv")
prest_PR <- fread(file = "despesas_contratadas_orgaos_partidarios_2018_PR.csv")
prest_RJ <- fread(file = "despesas_contratadas_orgaos_partidarios_2018_RJ.csv")
prest_RN <- fread(file = "despesas_contratadas_orgaos_partidarios_2018_RN.csv")
prest_RO <- fread(file = "despesas_contratadas_orgaos_partidarios_2018_RO.csv")
prest_RR <- fread(file = "despesas_contratadas_orgaos_partidarios_2018_RR.csv")
prest_RS <- fread(file = "despesas_contratadas_orgaos_partidarios_2018_RS.csv")
prest_SC <- fread(file = "despesas_contratadas_orgaos_partidarios_2018_SC.csv")
prest_SE <- fread(file = "despesas_contratadas_orgaos_partidarios_2018_SE.csv")
prest_SP <- fread(file = "despesas_contratadas_orgaos_partidarios_2018_SP.csv")
prest_TO <- fread(file = "despesas_contratadas_orgaos_partidarios_2018_TO.csv")
prest_ZZ <- fread(file = "despesas_contratadas_orgaos_partidarios_2018_ZZ.csv")

prest_2018 <- bind_rows(prest_AC, prest_AL, prest_AM, prest_AP, 
                        prest_BA, prest_BR, prest_CE, prest_DF, 
                        prest_ES, prest_GO, prest_MA, prest_MG, 
                        prest_MS, prest_MT, prest_PA, prest_PB, 
                        prest_PE, prest_PI, prest_PR, prest_RJ, 
                        prest_RN, prest_RO, prest_RR, prest_RS, 
                        prest_SC, prest_SE, prest_SP, prest_TO)


fwrite(prest_2018, file="prest_2018.csv")

result_pt <- filter(prest_2018, SG_PARTIDO == "PT")
result_mdb <- filter(prest_2018, SG_PARTIDO == "MDB")
result_psdb <- filter(prest_2018, SG_PARTIDO == "PSDB")
result_psb <- filter(prest_2018, SG_PARTIDO == "PSB")
result_pv <- filter(prest_2018, SG_PARTIDO == "PV")
result_prb <- filter(prest_2018, SG_PARTIDO == "PRB")
result_pv <- filter(prest_2018, SG_PARTIDO == "PV")
result_psol <- filter(prest_2018, SG_PARTIDO == "PSOL")
result_pmb <- filter(prest_2018, SG_PARTIDO == "PMB")
result_prtb <- filter(prest_2018, SG_PARTIDO == "PRTB")
result_ptb <- filter(prest_2018, SG_PARTIDO == "PTB")
result_pdt <- filter(prest_2018, SG_PARTIDO == "PDT")
result_dem <- filter(prest_2018, SG_PARTIDO == "DEM")
result_pcdob <- filter(prest_2018, SG_PARTIDO == "PCdoB")
result_ptc <- filter(prest_2018, SG_PARTIDO == "PTC")
result_psc <- filter(prest_2018, SG_PARTIDO == "PSC")
result_pmn <- filter(prest_2018, SG_PARTIDO == "PMN")
result_prp <- filter(prest_2018, SG_PARTIDO == "PRP")
result_pps <- filter(prest_2018, SG_PARTIDO == "PPS")
result_avante <- filter(prest_2018, SG_PARTIDO == "AVANTE")
result_pstu <- filter(prest_2018, SG_PARTIDO == "PSTU")
result_pcb <- filter(prest_2018, SG_PARTIDO == "PCB")
result_phs <- filter(prest_2018, SG_PARTIDO == "PHS")
result_dc <- filter(prest_2018, SG_PARTIDO == "DC")
result_pco <- filter(prest_2018, SG_PARTIDO == "PCO")
result_pode <- filter(prest_2018, SG_PARTIDO == "PODE")
result_psl <- filter(prest_2018, SG_PARTIDO == "PSL")
result_pr <- filter(prest_2018, SG_PARTIDO == "PR")
result_psd <- filter(prest_2018, SG_PARTIDO == "PSD")
result_ppl <- filter(prest_2018, SG_PARTIDO == "PPL")
result_patri <- filter(prest_2018, SG_PARTIDO == "PATRI")
result_pros <- filter(prest_2018, SG_PARTIDO == "PROS")
result_sd <- filter(prest_2018, SG_PARTIDO == "SOLIDARIEDADE")
result_novo <- filter(prest_2018, SG_PARTIDO == "NOVO")
result_rede <- filter(prest_2018, SG_PARTIDO == "REDE")

View(prest_2018)


fwrite(result_pt, file="result_pt.csv")
fwrite(result_mdb, file="result_mdb.csv")
fwrite(result_psdb, file="result_psdb.csv")
fwrite(result_psb, file="result_psb.csv")
fwrite(result_pv, file="result_pv.csv")
fwrite(result_prb, file="result_prb.csv")
fwrite(result_pv, file="result_pv.csv")
fwrite(result_psol, file="result_psol.csv")
fwrite(result_pmb, file="result_pmb.csv")
fwrite(result_prtb, file="result_prtb.csv")
fwrite(result_ptb, file="result_ptb.csv")
fwrite(result_pdt, file="result_pdt.csv")
fwrite(result_dem, file="result_dem.csv")
fwrite(result_pcdob, file="result_pcdob.csv")
fwrite(result_ptc, file="result_ptc.csv")
fwrite(result_psc, file="result_psc.csv")
fwrite(result_pmn, file="result_pmn.csv")
fwrite(result_prp, file="result_prp.csv")
fwrite(result_pps, file="result_pps.csv")
fwrite(result_avante, file="result_avante.csv")
fwrite(result_pstu, file="result_pstu.csv")
fwrite(result_pcb, file="result_pcb.csv")
fwrite(result_phs, file="result_phs.csv")
fwrite(result_dc, file="result_dc.csv")
fwrite(result_pco, file="result_pco.csv")
fwrite(result_pode, file="result_pode.csv")
fwrite(result_psl, file="result_psl.csv")
fwrite(result_pr, file="result_pr.csv")
fwrite(result_psd, file="result_psd.csv")
fwrite(result_ppl, file="result_ppl.csv")
fwrite(result_patri, file="result_patri.csv")
fwrite(result_pros, file="result_pros.csv")
fwrite(result_sd, file="result_sd.csv")
fwrite(result_novo, file="result_novo.csv")
fwrite(result_rede, file="result_rede.csv")

####

receita_AC <- fread(file = "receitas_orgaos_partidarios_2018_AC.csv")
receita_AL <- fread(file = "receitas_orgaos_partidarios_2018_AL.csv")
receita_AM <- fread(file = "receitas_orgaos_partidarios_2018_AM.csv")
receita_AP <- fread(file = "receitas_orgaos_partidarios_2018_AP.csv")
receita_BA <- fread(file = "receitas_orgaos_partidarios_2018_BA.csv")
receita_BR <- fread(file = "receitas_orgaos_partidarios_2018_BR.csv")
receita_CE <- fread(file = "receitas_orgaos_partidarios_2018_CE.csv")
receita_DF <- fread(file = "receitas_orgaos_partidarios_2018_DF.csv")
receita_ES <- fread(file = "receitas_orgaos_partidarios_2018_ES.csv")
receita_GO <- fread(file = "receitas_orgaos_partidarios_2018_GO.csv")
receita_MA <- fread(file = "receitas_orgaos_partidarios_2018_MA.csv")
receita_MG <- fread(file = "receitas_orgaos_partidarios_2018_MG.csv")
receita_MS <- fread(file = "receitas_orgaos_partidarios_2018_MS.csv")
receita_MT <- fread(file = "receitas_orgaos_partidarios_2018_MT.csv")
receita_PA <- fread(file = "receitas_orgaos_partidarios_2018_PA.csv")
receita_PB <- fread(file = "receitas_orgaos_partidarios_2018_PB.csv")
receita_PE <- fread(file = "receitas_orgaos_partidarios_2018_PE.csv")
receita_PI <- fread(file = "receitas_orgaos_partidarios_2018_PI.csv")
receita_PR <- fread(file = "receitas_orgaos_partidarios_2018_PR.csv")
receita_RJ <- fread(file = "receitas_orgaos_partidarios_2018_RJ.csv")
receita_RN <- fread(file = "receitas_orgaos_partidarios_2018_RN.csv")
receita_RO <- fread(file = "receitas_orgaos_partidarios_2018_RO.csv")
receita_RR <- fread(file = "receitas_orgaos_partidarios_2018_RR.csv")
receita_RS <- fread(file = "receitas_orgaos_partidarios_2018_RS.csv")
receita_SC <- fread(file = "receitas_orgaos_partidarios_2018_SC.csv")
receita_SE <- fread(file = "receitas_orgaos_partidarios_2018_SE.csv")
receita_SP <- fread(file = "receitas_orgaos_partidarios_2018_SP.csv")
receita_TO <- fread(file = "receitas_orgaos_partidarios_2018_TO.csv")
receita_ZZ <- fread(file = "receitas_orgaos_partidarios_2018_ZZ.csv")

receita_AC$SQ_CANDIDATO_DOADOR <- as.numeric(receita_AC$SQ_CANDIDATO_DOADOR)


receita_2018 <- bind_rows(receita_AC, receita_AL, receita_AM, receita_AP, 
                          receita_BA, receita_BR, receita_CE, receita_DF, 
                          receita_ES, receita_GO, receita_MA, receita_MG, 
                          receita_MS, receita_MT, receita_PA, receita_PB, 
                          receita_PE, receita_PI, receita_PR, receita_RJ, 
                          receita_RN, receita_RO, receita_RR, receita_RS, 
                          receita_SC, receita_SE, receita_SP, receita_TO)


fwrite(receita_2018, file="receita_2018.csv")
